"use client";
import { useState } from "react";
import Form from "./components/Form";
import Weeks from "./components/Week";
import { ArrowRight, Leaf, Activity, MessageCircle } from "lucide-react";

export default function Home() {
  const [data, setData] = useState({});
  const [showForm, setShowForm] = useState(false);

  if (showForm) {
    return (
      <main
        className="flex flex-col justify-center items-center h-full relative"
        style={{
          minHeight: "80vh",
          width: "100%",
        }}
      >
        {/* Background image with opacity */}
        <div
          className="absolute inset-0 z-0 bg-base-100"
          style={{
            backgroundImage: "url('/image.png')",
            backgroundSize: "cover",
            backgroundPosition: "center",
            opacity: 0.15,
          }}
        />
        {/* Content above background */}
        <div className="relative z-10 w-full flex flex-col items-center">
          {Object.keys(data).length !== 0 ? (
            <Weeks data={data} />
          ) : (
            <Form setData={setData} />
          )}
        </div>
      </main>
    );
  }

  return (
    <main className="flex flex-col min-h-screen bg-base-100 font-sans">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-32 flex flex-col items-center text-center px-4">
        <div className="absolute top-0 right-0 -mr-32 -mt-32 w-96 h-96 rounded-full bg-primary/20 blur-3xl opacity-50 z-0 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 -ml-32 -mb-32 w-96 h-96 rounded-full bg-secondary/20 blur-3xl opacity-50 z-0 pointer-events-none"></div>
        
        <div className="relative z-10 max-w-4xl mx-auto flex flex-col items-center">
          <div className="badge badge-primary badge-outline mb-6 py-4 px-6 text-sm font-semibold tracking-wider border-2">
            AI-POWERED NUTRITION
          </div>
          <h1 className="text-5xl md:text-7xl font-extrabold text-base-content leading-tight mb-8">
            Your Personal <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary">Diet Planner</span> <br className="hidden md:block"/> at Your Fingertips
          </h1>
          <p className="text-lg md:text-2xl text-base-content/70 max-w-2xl mb-12 font-medium">
            Achieve your health goals with custom meal plans generated by advanced AI. Chat with our virtual assistant for instant support and guidance.
          </p>
          <div className="flex gap-4">
            <button 
              onClick={() => setShowForm(true)}
              className="btn btn-primary btn-lg rounded-full shadow-xl hover:shadow-2xl hover:-translate-y-1 transition-all px-8 border-none"
            >
              Get Started Now <ArrowRight className="ml-2 w-5 h-5" />
            </button>
            <button 
              onClick={() => window.scrollTo({ top: 600, behavior: "smooth" })}
              className="btn btn-outline btn-lg rounded-full hover:-translate-y-1 transition-all px-8"
            >
              Learn More
            </button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-base-200/50 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Everything you need to succeed</h2>
            <p className="text-base-content/60 text-lg">Powerful features to help you manage your diet and lifestyle effectively.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="card bg-base-100 shadow-xl hover:-translate-y-2 transition-transform duration-300 border border-base-200">
              <div className="card-body items-center text-center p-8">
                <div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center text-primary mb-6 shadow-inner">
                  <Leaf className="w-10 h-10" />
                </div>
                <h3 className="card-title text-2xl mb-3">Personalized Plans</h3>
                <p className="text-base-content/70 leading-relaxed">Custom diet schedules tailored specifically for your body, lifestyle, and unique preferences.</p>
              </div>
            </div>
            
            <div className="card bg-base-100 shadow-xl hover:-translate-y-2 transition-transform duration-300 border border-base-200">
              <div className="card-body items-center text-center p-8">
                <div className="w-20 h-20 rounded-2xl bg-secondary/10 flex items-center justify-center text-secondary mb-6 shadow-inner">
                  <MessageCircle className="w-10 h-10" />
                </div>
                <h3 className="card-title text-2xl mb-3">AI Chat Assistant</h3>
                <p className="text-base-content/70 leading-relaxed">Have a question about what to eat? Ask our 24/7 intelligent chatbot for instant nutritional advice.</p>
              </div>
            </div>

            <div className="card bg-base-100 shadow-xl hover:-translate-y-2 transition-transform duration-300 border border-base-200">
              <div className="card-body items-center text-center p-8">
                <div className="w-20 h-20 rounded-2xl bg-accent/10 flex items-center justify-center text-accent mb-6 shadow-inner">
                  <Activity className="w-10 h-10" />
                </div>
                <h3 className="card-title text-2xl mb-3">Goal Tracking</h3>
                <p className="text-base-content/70 leading-relaxed">Monitor your daily macronutrients, visualize your progress, and stay on top of your fitness journey.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
